<?php

declare(strict_types=1);

$originalPremiseExample = <<<'MD'
## Logline

When a retiring lighthouse keeper intercepts a distress call on a maritime frequency that has been officially dead for thirty years, he must decide whether to report an impossible signal or honor the silence his predecessor died protecting.

## Premise

Elias Croft has three months left at North Stack Light, a stone tower the Coast Guard is converting to automated monitoring. His plan is simple: finish the winter, hand over the keys, and never hear the sea again. Then, on a storm night when the satellite link fails, his antique VHF monitor catches a spoken mayday on channel 16, decommissioned in 1994. The voice asks for "Stack Keeper" by name.

The Coast Guard wants a clean handover. Elias wants out. But every keeper who served here left a logbook entry about a signal they could never identify, and his predecessor's final page is blank except for a single frequency scribbled in the margin. Reporting the call opens an investigation that could delay decommissioning and trap Elias on the rock for another season. Staying quiet means letting a voice that sounds very much like a woman in her twenties call for help on a channel no ship should still be using.

## Central dramatic question

If the past is still transmitting, what does a man owe it when he has finally arranged a future without it?

## Why this story now

North Stack is one of the last staffed lights on this coast. Automation is sold as progress, but it also erases the human witness who notices when something is wrong. Elias is not a hero waiting to be chosen; he is a tired professional who built his identity around tending a machine the world no longer needs. The radio signal forces him to ask whether his vigilance ever mattered, or whether he stayed because leaving would mean admitting it did not.

## What this is not

This is not a ghost story with a twist you can guess in chapter two. The signal may have a mundane explanation, a cruel one, or none Elias can live with. The novel does not promise answers on the last page. It promises Elias cannot unhear what he heard, and that choice will cost him something real.

## Opening image

Elias on the gallery rail at first light, coffee going cold, watching the maintenance boat that will eventually take him away. The radio crackles once, a fragment of coordinates and a name he has not spoken aloud in twenty years. He writes nothing down. He goes inside to check the logbook his predecessor left open to a blank page.
MD;

return [
    'slug'                => 'plan-a-novel',
    'title'               => 'Plan a Novel',
    'tagline'             => 'From a spark of an idea to a chapter roadmap you can actually write from.',
    'description'         => "Most novels stall long before the blank page because the writer is holding premise, people, world, and structure in their head at once. This Cookbook separates those jobs into eighteen steps across seven stages. Enter the decisions you already know once: genre, theme, protagonist, rules of the world, and what you refuse to compromise. Each step asks you to approve one layer before the next, so you can explore without losing the thread. Checks along the way are decision-heavy: you are confirming the plan still matches the book you meant to write.",
    'primary_category'    => 'creative-worlds',
    'collections'         => [],
    'audience'            => 'Fiction writers planning a novel or novella before drafting',
    'outcome'             => 'A premise, cast map, world bible, conflict arc, act outline, chapter roadmap, scene beats, and revision priorities',
    'price_cents'         => null,
    'is_executable'       => false,
    'accent'              => 'lilac',
    'difficulty'          => 'Advanced',
    'est_minutes'         => 240,
    'demo_completed_runs' => 156,
    'demo_avg_rating'     => 4.6,
    'sort_order'          => 5,
    'stages' => [
        ['title' => 'Spark', 'summary' => 'Find the idea worth a year of your life and name the shelf it belongs on.'],
        ['title' => 'Promise', 'summary' => 'Define what the reader is signing up for and what they should feel at the end.'],
        ['title' => 'People', 'summary' => 'Build the characters who will carry the weight of the story.'],
        ['title' => 'World', 'summary' => 'Ground the story in rules, constraints, and the culture of the place.'],
        ['title' => 'Conflict', 'summary' => 'Engineer pressure that escalates and breaks open at the midpoint.'],
        ['title' => 'Structure', 'summary' => 'Map acts, chapters, and scene beats before momentum fades.'],
        ['title' => 'Continuity', 'summary' => 'Lock your decisions and name what to revise first when you draft.'],
    ],
    'fields' => [
        [
            'field_key'    => 'working_title',
            'label'        => 'Working title',
            'type'         => 'text',
            'help'         => 'A placeholder name is fine. Every Recipe refers to the project by this title until you pick the real one.',
            'placeholder'  => 'e.g. The Keeper\'s Frequency',
            'sample_value' => "The Keeper's Frequency",
        ],
        [
            'field_key'    => 'genre',
            'label'        => 'Genre',
            'type'         => 'text',
            'help'         => 'Primary shelf and any secondary label. Be specific enough that a bookseller would know where to put it.',
            'placeholder'  => 'e.g. Literary fiction with a mystery thread',
            'sample_value' => 'Literary fiction with a mystery thread',
        ],
        [
            'field_key'    => 'tone',
            'label'        => 'Tone',
            'type'         => 'text',
            'help'         => 'The emotional texture of the prose and scenes, not the plot. Two or three adjectives beat a paragraph.',
            'placeholder'  => 'e.g. Quiet, atmospheric, morally unresolved',
            'sample_value' => 'Quiet, atmospheric, morally unresolved',
        ],
        [
            'field_key'    => 'target_reader',
            'label'        => 'Target reader',
            'type'         => 'textarea',
            'help'         => 'Who picks this up and why today? Describe the reader\'s taste, not their demographics.',
            'placeholder'  => 'Who is this for, and what do they love to feel while reading?',
            'sample_value' => "Readers who finish books slowly because they reread sentences that sound like the sea at night. They want character over spectacle, and they trust an author who leaves one question unanswered if the emotional cost is honest.",
        ],
        [
            'field_key'    => 'core_theme',
            'label'        => 'Core theme',
            'type'         => 'textarea',
            'help'         => 'The question the novel keeps asking, not a moral stamped on the cover. One sentence plus one sentence on why it matters to you.',
            'placeholder'  => 'What is this book really about?',
            'sample_value' => "What do we owe the dead when the living need us more? I keep returning to this because my own family left things unsaid until it was too late to say them.",
        ],
        [
            'field_key'    => 'protagonist_name',
            'label'        => 'Protagonist name',
            'type'         => 'text',
            'help'         => 'First name or full name, however you think about them while planning.',
            'placeholder'  => 'e.g. Elias Croft',
            'sample_value' => 'Elias Croft',
        ],
        [
            'field_key'    => 'protagonist_want',
            'label'        => 'Protagonist want',
            'type'         => 'textarea',
            'help'         => 'The conscious goal driving them at the opening. Specific and achievable on the surface.',
            'placeholder'  => 'What do they think they are trying to get?',
            'sample_value' => 'Finish his final season at North Stack Light, complete the handover to automated monitoring, and leave the coast without looking back.',
        ],
        [
            'field_key'    => 'protagonist_flaw',
            'label'        => 'Protagonist flaw',
            'type'         => 'textarea',
            'help'         => 'The habit or belief that makes the want harder and the theme personal. Tie it to a choice they make badly.',
            'placeholder'  => 'What pattern gets them into trouble?',
            'sample_value' => 'He treats every unanswered question as a personal failure he must solve alone, which makes him hide problems from the people who could actually help.',
        ],
        [
            'field_key'    => 'antagonist_force',
            'label'        => 'Antagonist force',
            'type'         => 'textarea',
            'help'         => 'Person, institution, or pressure that opposes the protagonist. Name what they represent, not just what they do.',
            'placeholder'  => 'Who or what pushes back hardest?',
            'sample_value' => "Commander Hale of the regional Coast Guard, who needs a clean decommissioning on schedule, and the legacy of Elias's predecessor, whose unfinished logbook implies the station hides a problem Hale's report cannot afford.",
        ],
        [
            'field_key'    => 'setting_era',
            'label'        => 'Setting and era',
            'type'         => 'text',
            'help'         => 'Where and when the story mostly lives. One vivid phrase beats a travel brochure.',
            'placeholder'  => 'e.g. Present-day North Atlantic coast, last staffed lighthouse season',
            'sample_value' => 'Present-day North Atlantic coast, final winter of staffed operation at North Stack Light',
        ],
        [
            'field_key'    => 'world_rule_one',
            'label'        => 'World rule one',
            'type'         => 'textarea',
            'help'         => 'A fact about how this world works that later Recipes must not contradict. Make it testable in a scene.',
            'placeholder'  => 'One rule the plot will depend on',
            'sample_value' => 'The lighthouse radio array still picks up maritime frequencies that mainland towers cannot reach because of the rock\'s height and the old relay hardware.',
        ],
        [
            'field_key'    => 'world_rule_two',
            'label'        => 'World rule two',
            'type'         => 'textarea',
            'help'         => 'A second rule that creates constraint or mystery. If it never causes trouble, cut it later.',
            'placeholder'  => 'Another rule with story consequences',
            'sample_value' => 'Every keeper who served at North Stack left a logbook entry about a signal they could never identify; Elias is the first to consider reporting one.',
        ],
        [
            'field_key'    => 'story_length',
            'label'        => 'Story length',
            'type'         => 'select',
            'help'         => 'Structure Recipes scale to this target. You can change it later, but decide now so the roadmap is honest.',
            'options'      => ['Novel', 'Novella'],
            'sample_value' => 'Novel',
        ],
        [
            'field_key'    => 'pov_style',
            'label'        => 'POV style',
            'type'         => 'select',
            'help'         => 'Every structure Recipe assumes this perspective unless you approve a change in Continuity.',
            'options'      => ['First person', 'Third person limited', 'Third person omniscient', 'Multiple viewpoints'],
            'sample_value' => 'Third person limited',
        ],
        [
            'field_key'    => 'comp_titles',
            'label'        => 'Comp titles',
            'type'         => 'textarea',
            'help'         => 'Two or three published books yours would sit beside. Say what you share and what you do differently.',
            'placeholder'  => "Title by Author: what you borrow and what you leave behind",
            'sample_value' => "The Light Between Oceans by M.L. Stedman: isolation, moral choice, and the sea as witness, but without a baby at the center\nGilead by Marilynne Robinson: quiet interiority and grace under pressure, but with a ticking institutional deadline",
        ],
        [
            'field_key'    => 'non_negotiables',
            'label'        => 'Non-negotiables',
            'type'         => 'textarea',
            'help'         => 'Creative boundaries you will not cross. Recipes treat these as hard limits, not suggestions.',
            'placeholder'  => 'What must stay true no matter how the plot shifts?',
            'sample_value' => "No supernatural explanation for the radio signal. The ending may be ambiguous but not cynical. Elias must make the final choice himself; no rescue from a hidden expert.",
        ],
    ],
    'recipes' => [
        [
            'stage_position'   => 1,
            'slug'             => 'original-premise',
            'title'            => 'Original Premise',
            'summary'          => 'Distill your idea into a logline, a premise paragraph, and the question the novel keeps asking.',
            'why_it_matters'   => 'Everything downstream quotes this Recipe. Writers who skip a clear premise end up with beautiful worldbuilding and a protagonist who has nothing to do. Ten honest minutes here prevent three months of drift.',
            'unlocks_text'     => 'Approve the premise and the Genre and Tone Recipe can test whether the idea fits the shelf you want.',
            'est_minutes'      => 12,
            'prompt_template'  => null,
            'example_response' => $originalPremiseExample,
            'checks' => [
                ['label' => 'The idea feels specific to you', 'help' => 'Swap the names and setting and it still could not belong to another writer.'],
                ['label' => 'Conflict is visible in the premise', 'help' => 'Someone wants something, something pushes back, and waiting is not free.'],
                ['label' => 'You can state the central question', 'help' => 'In one sentence, without summarizing the plot.'],
            ],
        ],
        [
            'stage_position'   => 1,
            'slug'             => 'genre-and-tone',
            'title'            => 'Genre and Tone',
            'summary'          => 'Place the book on a shelf, name the emotional register, and flag where you might break expectations.',
            'why_it_matters'   => 'Genre is a promise, not a label. Readers forgive a lot if the tone stays honest. This Recipe forces you to decide what you are delivering before you write scenes that belong in a different book.',
            'unlocks_text'     => 'Approving this unlocks Promise stage: what the reader signs up for and what they should feel at the end.',
            'est_minutes'      => 10,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Genre matches the premise', 'help' => 'The shelf you chose could carry the central question without misleading the reader.'],
                ['label' => 'Tone is actionable', 'help' => 'You could describe a scene as "too light" or "too cruel" using the tone words you picked.'],
                ['label' => 'Comp titles are honest', 'help' => 'You named what you share with each comp and what you deliberately do differently.'],
            ],
        ],
        [
            'stage_position'   => 2,
            'slug'             => 'reader-promise',
            'title'            => 'Reader Promise',
            'summary'          => 'Write the contract you are making with the reader on page one.',
            'why_it_matters'   => 'Every novel makes a promise before chapter three: this will be a mystery, a romance, a reckoning. Break it accidentally and readers feel cheated even if the prose is fine. Naming the promise now lets you keep or subvert it on purpose.',
            'unlocks_text'     => 'Approve the promise and the Emotional Payoff Recipe defines where that contract lands.',
            'est_minutes'      => 12,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Promise fits your target reader', 'help' => 'The reader you described would knowingly pick up this book for this reason.'],
                ['label' => 'Opening and ending align', 'help' => 'The promise you make could plausibly be kept or honestly broken by the final chapter.'],
                ['label' => 'No bait and switch', 'help' => 'You are not promising a thriller beat if the book is really about interior change.'],
            ],
        ],
        [
            'stage_position'   => 2,
            'slug'             => 'emotional-payoff',
            'title'            => 'Emotional Payoff',
            'summary'          => 'Name the feeling the reader should carry after the last page, and what earns it.',
            'why_it_matters'   => 'Plot is what happens; payoff is what it meant. Writers who plan only events often nail the climax and still lose the reader because the emotional invoice was never sent. This Recipe makes you earn the ending before you write it.',
            'unlocks_text'     => 'Approving this unlocks People stage: protagonist, antagonist pressure, and the supporting cast.',
            'est_minutes'      => 12,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Payoff connects to theme', 'help' => 'The feeling at the end answers the core theme question, even if the plot question does not.'],
                ['label' => 'Earned, not declared', 'help' => 'You named scenes or choices that must happen for the payoff to land, not just adjectives.'],
                ['label' => 'Matches your non-negotiables', 'help' => 'The payoff does not require breaking a boundary you said was fixed.'],
            ],
        ],
        [
            'stage_position'   => 3,
            'slug'             => 'protagonist-profile',
            'title'            => 'Protagonist Profile',
            'summary'          => 'Build a working portrait: want, need, flaw, and the lie they believe at the opening.',
            'why_it_matters'   => 'A premise without a person inside it is a pitch deck. This Recipe turns your Pantry notes into a protagonist who can make wrong choices that matter. If you cannot describe what they want and what they need differently, the middle will sag.',
            'unlocks_text'     => 'Approve the profile and Antagonist Pressure Recipe can push against someone specific.',
            'est_minutes'      => 13,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Want and need diverge', 'help' => 'What they chase at the opening is not the same as what would actually heal them.'],
                ['label' => 'Flaw drives plot', 'help' => 'At least one upcoming conflict gets worse because of how they are, not bad luck alone.'],
                ['label' => 'Voice feels distinct', 'help' => 'You could pick their dialogue out of a lineup without dialogue tags.'],
            ],
        ],
        [
            'stage_position'   => 3,
            'slug'             => 'antagonist-pressure',
            'title'            => 'Antagonist Pressure',
            'summary'          => 'Define who or what opposes the protagonist and why their goals cannot coexist.',
            'why_it_matters'   => 'Villains who exist to be evil are boring; pressure that reflects the theme is not. This Recipe forces the opposition to attack the protagonist\'s flaw, not just block their want.',
            'unlocks_text'     => 'Approving this unlocks Supporting Cast Map: allies, foils, and people who complicate the middle.',
            'est_minutes'      => 13,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Opposition is principled', 'help' => 'The antagonist force has a reason that makes sense from inside their own logic.'],
                ['label' => 'Pressure hits the flaw', 'help' => 'Their strategy exploits how the protagonist tends to make things worse.'],
                ['label' => 'Stakes are personal', 'help' => 'Losing hurts this protagonist in a way that would not be identical for a stranger.'],
            ],
        ],
        [
            'stage_position'   => 3,
            'slug'             => 'supporting-cast-map',
            'title'            => 'Supporting Cast Map',
            'summary'          => 'List the characters who recur, what each one wants from the protagonist, and when they enter.',
            'why_it_matters'   => 'Supporting characters are not furniture. Each one should change the cost of a decision or mirror a path not taken. Mapping them now prevents the draft from filling with names who appear once to deliver exposition.',
            'unlocks_text'     => 'Approving this unlocks World stage: rules, constraints, and culture of place.',
            'est_minutes'      => 12,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Every name earns a return', 'help' => 'Each listed character appears more than once or carries information that pays off later.'],
                ['label' => 'Relationships create choice', 'help' => 'At least two supporting characters pull the protagonist in incompatible directions.'],
                ['label' => 'Cast size fits length', 'help' => 'A novella map is leaner than a novel map; you did not plan an ensemble you cannot serve.'],
            ],
        ],
        [
            'stage_position'   => 4,
            'slug'             => 'world-rules',
            'title'            => 'World Rules',
            'summary'          => 'Expand your Pantry rules into a short bible: what is true, what is forbidden, and what costs extra.',
            'why_it_matters'   => 'Inconsistent rules break trust faster than a typo. Literary fiction still has physics, institutions, and habits. Writing the rules down lets you break them on purpose instead of by accident.',
            'unlocks_text'     => 'Approve the rules and Setting Constraints Recipe grounds them in time and place.',
            'est_minutes'      => 13,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Rules can be tested', 'help' => 'Each rule could appear as a concrete obstacle or clue in a scene.'],
                ['label' => 'No contradictions with premise', 'help' => 'Nothing here makes the approved premise impossible without explanation.'],
                ['label' => 'Limits are as clear as powers', 'help' => 'You named what characters cannot do or cannot know, not just what they can.'],
            ],
        ],
        [
            'stage_position'   => 4,
            'slug'             => 'setting-constraints',
            'title'            => 'Setting Constraints',
            'summary'          => 'Map where scenes happen, what the location forbids, and how isolation or crowd shapes choices.',
            'why_it_matters'   => 'Setting is not wallpaper. A lighthouse in winter and a city apartment create different kinds of secrecy. Constraints like weather, distance, and who can hear you talking force better scenes.',
            'unlocks_text'     => 'Approving this unlocks Culture of Place: customs, language, and what locals know that outsiders do not.',
            'est_minutes'      => 12,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Locations differ in pressure', 'help' => 'At least two settings push different kinds of decisions, not just different scenery.'],
                ['label' => 'Era details matter', 'help' => 'Technology, law, or custom from your era changes what a character can plausibly do.'],
                ['label' => 'Travel time is honest', 'help' => 'Characters cannot be in two distant places without the story accounting for the gap.'],
            ],
        ],
        [
            'stage_position'   => 4,
            'slug'             => 'culture-of-place',
            'title'            => 'Culture of Place',
            'summary'          => 'Capture how people talk, what they hide, and the unwritten rules visitors break.',
            'why_it_matters'   => 'Culture turns a location into a society. Two scenes in the same kitchen feel different when you know who is allowed to speak first. This Recipe gives you texture that separates your book from a generic backdrop.',
            'unlocks_text'     => 'Approving this unlocks Conflict stage: engine, escalation, and midpoint shift.',
            'est_minutes'      => 13,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Customs affect plot', 'help' => 'At least one cultural rule makes a protagonist choice harder or riskier.'],
                ['label' => 'Outsider status is defined', 'help' => 'You know who belongs, who does not, and what mistake exposes an outsider.'],
                ['label' => 'Details are specific', 'help' => 'You avoided generic "small town" or "big city" shorthand in favor of named habits.'],
            ],
        ],
        [
            'stage_position'   => 5,
            'slug'             => 'conflict-engine',
            'title'            => 'Conflict Engine',
            'summary'          => 'Diagram the opposing wants that collide and the question each act must answer.',
            'why_it_matters'   => 'If nothing is actively being contested, you have a situation, not a story. The engine names what regenerates tension after each scene ends so the middle does not become a pleasant tour of your research.',
            'unlocks_text'     => 'Approve the engine and Stakes Escalation Recipe raises the cost of each pass through it.',
            'est_minutes'      => 15,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Both sides can win locally', 'help' => 'Protagonist and opposition each score points; neither is a pushover.'],
                ['label' => 'Theme is embedded', 'help' => 'The central collision reflects your core theme, not just a job dispute.'],
                ['label' => 'Escalation path is visible', 'help' => 'You can name what makes chapter ten harder than chapter two.'],
            ],
        ],
        [
            'stage_position'   => 5,
            'slug'             => 'stakes-escalation',
            'title'            => 'Stakes Escalation',
            'summary'          => 'Chart how public, personal, and irreversible the cost becomes act by act.',
            'why_it_matters'   => 'Flat stakes make readers put the book down to make tea. Escalation is not louder explosions; it is fewer places to hide. This Recipe makes you decide what can still be taken away when the protagonist thinks they have already lost enough.',
            'unlocks_text'     => 'Approving this unlocks Midpoint Shift: the revelation or decision that redefines the second half.',
            'est_minutes'      => 14,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Stakes widen, not just repeat', 'help' => 'Each escalation adds a new category of loss, not the same threat again.'],
                ['label' => 'Personal cost is named', 'help' => 'You know what relationship or identity is on the line, not just plot machinery.'],
                ['label' => 'Non-negotiables hold', 'help' => 'Raising stakes did not require a cheat you already ruled out.'],
            ],
        ],
        [
            'stage_position'   => 5,
            'slug'             => 'midpoint-shift',
            'title'            => 'Midpoint Shift',
            'summary'          => 'Design the turn that moves the protagonist from reacting to choosing, or from wrong goal to true need.',
            'why_it_matters'   => 'The midpoint is where many novels quietly die in the drawer. Before it, the protagonist could still walk away. After it, they cannot, or they choose not to. Naming the shift now keeps the second half from being more of the first half.',
            'unlocks_text'     => 'Approving this unlocks Structure stage: act outline, chapter roadmap, and scene beats.',
            'est_minutes'      => 15,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Shift is a decision or revelation', 'help' => 'Something concrete changes; it is not a mood that drifts.'],
                ['label' => 'Before and after differ', 'help' => 'You can describe what the protagonist would do in act three that act one them would refuse.'],
                ['label' => 'Connects to flaw and theme', 'help' => 'The shift forces the protagonist to confront the lie they believed at the opening.'],
            ],
        ],
        [
            'stage_position'   => 6,
            'slug'             => 'act-outline',
            'title'            => 'Act Outline',
            'summary'          => 'Block the story into acts with turning points, reversals, and the climax decision.',
            'why_it_matters'   => 'Acts are not formula; they are readability. Readers feel rhythm even when they cannot name it. This Recipe gives you permission to cut beautiful scenes that belong in the wrong act.',
            'unlocks_text'     => 'Approve the act outline and Chapter Roadmap Recipe breaks act one into draftable units.',
            'est_minutes'      => 16,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Each act has a job', 'help' => 'You can state in one sentence what each act accomplishes for the reader promise.'],
                ['label' => 'Midpoint sits in the middle', 'help' => 'The approved midpoint shift lands roughly halfway through the planned length.'],
                ['label' => 'Climax is a choice', 'help' => 'The final act turns on what the protagonist decides, not only what happens to them.'],
            ],
        ],
        [
            'stage_position'   => 6,
            'slug'             => 'chapter-roadmap',
            'title'            => 'Chapter Roadmap',
            'summary'          => 'List chapters with POV, purpose, and the question each chapter must answer.',
            'why_it_matters'   => 'Chapters are how readers breathe and how you measure progress while drafting. A roadmap scaled to your story length stops you from writing six setup chapters because you were afraid to start the real fight.',
            'unlocks_text'     => 'Approving this unlocks Scene Beat Sheet: the first chapters opened into draft-ready beats.',
            'est_minutes'      => 15,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Chapter count fits length', 'help' => 'Novel and novella targets produce different totals, and yours looks intentional.'],
                ['label' => 'Each chapter turns', 'help' => 'Every chapter changes something: information, relationship, or option.'],
                ['label' => 'POV plan is consistent', 'help' => 'Viewpoint choices match your Pantry POV style unless you flagged a deliberate exception.'],
            ],
        ],
        [
            'stage_position'   => 6,
            'slug'             => 'scene-beat-sheet',
            'title'            => 'Scene Beat Sheet',
            'summary'          => 'Break opening chapters into scenes with goal, conflict, and outcome beats.',
            'why_it_matters'   => 'Beats are where planning meets prose. Writers who jump from outline to draft without beats often rewrite chapter one ten times. This Recipe gives you a runway long enough to find the voice without planning the whole book scene by scene.',
            'unlocks_text'     => 'Approving this unlocks Continuity stage: a guide for draft decisions and revision priorities.',
            'est_minutes'      => 16,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Every scene has a goal', 'help' => 'Each scene names what the viewpoint character wants before the scene ends.'],
                ['label' => 'Outcomes vary', 'help' => 'Not every scene ends in success or failure the same way; mix victory, setback, and complication.'],
                ['label' => 'Opening delivers the promise', 'help' => 'The first scenes show the reader the book you promised in stage two.'],
            ],
        ],
        [
            'stage_position'   => 7,
            'slug'             => 'continuity-guide',
            'title'            => 'Continuity Guide',
            'summary'          => 'Compile the decisions, timelines, and names that must stay consistent through drafting.',
            'why_it_matters'   => 'Drafting invents details faster than memory keeps them. A continuity guide is not bureaucracy; it is the place you check whether chapter twelve broke a rule from chapter two on purpose or by mistake.',
            'unlocks_text'     => 'Approve the guide and Revision Priorities Recipe names what to fix first when the draft exists.',
            'est_minutes'      => 14,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Rules are cross-referenced', 'help' => 'World rules, culture notes, and cast map agree; contradictions are flagged for resolution.'],
                ['label' => 'Timeline is sketched', 'help' => 'You know how much story time passes and which events cannot move.'],
                ['label' => 'Branch decisions are recorded', 'help' => 'Creative choices you made along the way are written down so you do not reopen them every session.'],
            ],
        ],
        [
            'stage_position'   => 7,
            'slug'             => 'revision-priorities',
            'title'            => 'Revision Priorities',
            'summary'          => 'Rank what to fix in early drafts: structure, character, prose, or research gaps.',
            'why_it_matters'   => 'Revision without priority is polishing sentences on a chapter you will cut. This Recipe names the order of operations so your first read-through changes the book, not just the commas.',
            'unlocks_text'     => 'Approving this completes the Cookbook plan and opens your Project Kit export when this Cookbook ships.',
            'est_minutes'      => 13,
            'prompt_template'  => null,
            'example_response' => null,
            'checks' => [
                ['label' => 'Structure before syntax', 'help' => 'Your first pass targets act and scene problems, not word-level fussing.'],
                ['label' => 'Theme check included', 'help' => 'At least one revision pass asks whether the ending still answers the core theme.'],
                ['label' => 'Non-negotiables on the list', 'help' => 'Your fixed boundaries appear as explicit review items, not hopes.'],
            ],
        ],
    ],
];
