<?php

declare(strict_types=1);

namespace SousMeow\Services;

use SousMeow\Core\Config;
use SousMeow\Models\Artifact;
use SousMeow\Models\PantryField;
use SousMeow\Models\Project;
use ZipArchive;

/**
 * Builds the exported Project Kit: a zip holding one Markdown file per
 * approved Artifact plus a README manifest describing the Pantry and
 * the provenance of every file. Zips are written outside the web root
 * and only served through the authorized download route.
 */
final class ProjectKit
{
    /**
     * @param array<string, mixed> $project
     * @param array<string, mixed> $cookbook
     * @return array{filename: string, path: string, size: int, count: int}
     */
    public static function build(array $project, array $cookbook): array
    {
        $projectId = (int) $project['id'];
        $approved = Artifact::approvedByRecipe($projectId);

        $dir = rtrim(Config::string('exports.dir'), '/');
        if (!is_dir($dir)) {
            mkdir($dir, 0775, true);
        }

        $slug = self::slugify((string) $project['title']);
        $filename = sprintf('sousmeow-kit-%s-%s.zip', $slug !== '' ? $slug : 'project', gmdate('Ymd-His'));
        $path = $dir . '/' . $filename;

        $zip = new ZipArchive();
        if ($zip->open($path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException('Could not create the export archive.');
        }

        $fileList = [];
        foreach (array_values($approved) as $index => $artifact) {
            $name = sprintf('%02d-%s.md', $index + 1, (string) $artifact['recipe_slug']);
            $fileList[] = ['name' => $name, 'artifact' => $artifact];
            $zip->addFromString($name, self::artifactFile($artifact));
        }
        $zip->addFromString('README.md', self::manifest($project, $cookbook, $fileList));
        $zip->close();

        return [
            'filename' => $filename,
            'path'     => $path,
            'size'     => (int) (filesize($path) ?: 0),
            'count'    => count($fileList),
        ];
    }

    /** @param array<string, mixed> $artifact */
    private static function artifactFile(array $artifact): string
    {
        $header = sprintf(
            "# %s\n\n> Recipe %d of the %s. Approved version v%d%s.\n\n---\n\n",
            $artifact['recipe_title'],
            (int) $artifact['recipe_position'],
            'SousMeow Project Kit',
            (int) $artifact['version_no'],
            $artifact['source'] === 'example' ? ' (sample data from Demo Mode)' : ''
        );
        return $header . rtrim((string) $artifact['content']) . "\n";
    }

    /**
     * @param array<string, mixed> $project
     * @param array<string, mixed> $cookbook
     * @param list<array{name: string, artifact: array<string, mixed>}> $fileList
     */
    private static function manifest(array $project, array $cookbook, array $fileList): string
    {
        $lines = [];
        $lines[] = '# ' . $project['title'] . ': Project Kit';
        $lines[] = '';
        $lines[] = sprintf(
            'Cooked with the **%s** Cookbook in SousMeow and exported on %s UTC.',
            $cookbook['title'],
            gmdate('Y-m-d H:i')
        );
        $lines[] = '';
        $lines[] = 'Every file below was generated by an AI of the author\'s choosing, then human-reviewed';
        $lines[] = 'against the Recipe\'s Quality Checks and explicitly approved before export.';
        $lines[] = '';
        $lines[] = '## Files';
        $lines[] = '';
        foreach ($fileList as $entry) {
            $a = $entry['artifact'];
            $sample = $a['source'] === 'example' ? ', sample data' : '';
            $lines[] = sprintf('- `%s`: %s (v%d approved%s)', $entry['name'], $a['recipe_title'], (int) $a['version_no'], $sample);
        }
        $lines[] = '';
        $lines[] = '## Pantry (the ingredients everything was cooked from)';
        $lines[] = '';

        $values = Project::pantryValues((int) $project['id']);
        foreach (PantryField::forCookbook((int) $project['cookbook_id']) as $field) {
            $raw = trim($values[(int) $field['id']] ?? '');
            if ($field['type'] === 'multiselect') {
                $decoded = json_decode($raw, true);
                $raw = is_array($decoded) ? implode(', ', $decoded) : $raw;
            }
            if (str_contains($raw, "\n")) {
                $lines[] = '- **' . $field['label'] . ':**';
                foreach (explode("\n", $raw) as $part) {
                    if (trim($part) !== '') {
                        $lines[] = '  - ' . trim($part);
                    }
                }
            } else {
                $lines[] = '- **' . $field['label'] . ':** ' . ($raw !== '' ? $raw : '(empty)');
            }
        }
        $lines[] = '';
        return implode("\n", $lines);
    }

    private static function slugify(string $text): string
    {
        $slug = strtolower(trim($text));
        $slug = (string) preg_replace('/[^a-z0-9]+/', '-', $slug);
        return trim(substr($slug, 0, 40), '-');
    }
}
